### PR TITLE
Fix the GlobalParentOccurence spelling

### PR DESCRIPTION
**Pull request by robUx4**
As suggested in AUTH48 7) item it takes 2 'r'.

### CODE REVIEW

**Comment by retokromer** [comment]
Please fix occurence > occurrence also at line 432.

**Comment by robUx4** [comment]
> Please fix occurence > occurrence also at line 432.

Good catch !

**Review by mbunkus — CHANGES_REQUESTED** [review]
After the change the whole assignment table isn't aligned on the `=` anymore.

**Comment by robUx4** [comment]
Good catch too. And good thing we still have some spare spaces on the .txt version.

**Review by mbunkus — APPROVED** [review]
Thanks!

**Review by retokromer — APPROVED** [review]

**Review by dericed — APPROVED** [review]
lgtm, thx

**Pull request merged**
