### PR TITLE
Use the 2003 correction of the ITU V42 CRC

### PR DESCRIPTION
**Pull request by robUx4**
As suggested in AUTH48 20)

### CODE REVIEW

**Review by mbunkus — APPROVED** [review]

**Review by retokromer — APPROVED** [review]

**Comment by dericed** [comment]
I see the 2002 version at https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-V.42-200203-I!!PDF-E&type=items but can not find the 2003 version that you reference. Note that the AUTH48 review recommended 2002 as well.

**Comment by robUx4** [comment]
I found it here https://www.itu.int/rec/T-REC-V.42/en
Except it's just a correction in 2003. I'll update the PR.

**Review by dericed — COMMENTED** [review]
There’s an anchor conflict between 2002 and 2003

**Comment by robUx4** [comment]
Fixed

**Review by dericed — APPROVED** [review]

**Pull request merged**
