### PR TITLE
document XEBML expression

### PR DESCRIPTION
**Pull request by dericed**
This is meant to standardize a method of representing fragmentary or
whole expressions of EBML in textual XML.

### CODE REVIEW

**Comment by dericed** [comment]
This PR is somewhat related to the discussions in https://github.com/Matroska-Org/matroska-specification/pull/99 on standardizing a textual representation of EBML.

**Comment by dericed** [comment]
Also pinging @vi since the entire scope of https://github.com/vi/mkvparse is to transfer EBML back and forth into textual representations.

**Comment by vi** [comment]
Is there already some more or less complete example of XEBML document in relation to Matroska?

**Comment by dericed** [comment]
@vi a full XEBML of the Matroska Segment would like like this, please note the content is fake but set according to data type

```xml
<?xml version="1.0"?>
<XEBML>
  <Segment>
    <SeekHead>
      <Seek>
        <SeekID>1A45DFA3</SeekID>
        <SeekPosition>1</SeekPosition>
      </Seek>
    </SeekHead>
    <Info>
      <SegmentUID>1A45DFA3</SegmentUID>
      <SegmentFilename>utf-8</SegmentFilename>
      <PrevUID>1A45DFA3</PrevUID>
      <PrevFilename>utf-8</PrevFilename>
      <NextUID>1A45DFA3</NextUID>
      <NextFilename>utf-8</NextFilename>
      <SegmentFamily>1A45DFA3</SegmentFamily>
      <ChapterTranslate>
        <ChapterTranslateEditionUID>1</ChapterTranslateEditionUID>
        <ChapterTranslateCodec>1</ChapterTranslateCodec>
        <ChapterTranslateID>1A45DFA3</ChapterTranslateID>
      </ChapterTranslate>
      <TimecodeScale>1</TimecodeScale>
      <Duration>0x1p+0</Duration>
      <DateUTC>0</DateUTC>
      <Title>utf-8</Title>
      <MuxingApp>utf-8</MuxingApp>
      <WritingApp>utf-8</WritingApp>
    </Info>
    <Cluster>
      <Timecode>1</Timecode>
      <SilentTracks>
        <SilentTrackNumber>1</SilentTrackNumber>
      </SilentTracks>
      <Position>1</Position>
      <PrevSize>1</PrevSize>
      <SimpleBlock>1A45DFA3</SimpleBlock>
      <BlockGroup>
        <Block>1A45DFA3</Block>
        <BlockVirtual>1A45DFA3</BlockVirtual>
        <BlockAdditions>
          <BlockMore>
            <BlockAddID>1</BlockAddID>
            <BlockAdditional>1A45DFA3</BlockAdditional>
          </BlockMore>
        </BlockAdditions>
        <BlockDuration>1</BlockDuration>
        <ReferencePriority>1</ReferencePriority>
        <ReferenceBlock>-1</ReferenceBlock>
        <ReferenceVirtual>-1</ReferenceVirtual>
        <CodecState>1A45DFA3</CodecState>
        <DiscardPadding>-1</DiscardPadding>
        <Slices>
          <TimeSlice>
            <LaceNumber>1</LaceNumber>
            <FrameNumber>1</FrameNumber>
            <BlockAdditionID>1</BlockAdditionID>
            <Delay>1</Delay>
            <SliceDuration>1</SliceDuration>
          </TimeSlice>
        </Slices>
        <ReferenceFrame>
          <ReferenceOffset>1</ReferenceOffset>
          <ReferenceTimeCode>1</ReferenceTimeCode>
        </ReferenceFrame>
      </BlockGroup>
      <EncryptedBlock>1A45DFA3</EncryptedBlock>
    </Cluster>
    <Tracks>
      <TrackEntry>
        <TrackNumber>1</TrackNumber>
        <TrackUID>1</TrackUID>
        <TrackType>1</TrackType>
        <FlagEnabled>1</FlagEnabled>
        <FlagDefault>1</FlagDefault>
        <FlagForced>1</FlagForced>
        <FlagLacing>1</FlagLacing>
        <MinCache>1</MinCache>
        <MaxCache>1</MaxCache>
        <DefaultDuration>1</DefaultDuration>
        <DefaultDecodedFieldDuration>1</DefaultDecodedFieldDuration>
        <TrackTimecodeScale>0x1p+0</TrackTimecodeScale>
        <TrackOffset>-1</TrackOffset>
        <MaxBlockAdditionID>1</MaxBlockAdditionID>
        <Name>utf-8</Name>
        <Language>string</Language>
        <LanguageIETF>string</LanguageIETF>
        <CodecID>string</CodecID>
        <CodecPrivate>1A45DFA3</CodecPrivate>
        <CodecName>utf-8</CodecName>
        <AttachmentLink>1</AttachmentLink>
        <CodecSettings>utf-8</CodecSettings>
        <CodecInfoURL>string</CodecInfoURL>
        <CodecDownloadURL>string</CodecDownloadURL>
        <CodecDecodeAll>1</CodecDecodeAll>
        <TrackOverlay>1</TrackOverlay>
        <CodecDelay>1</CodecDelay>
        <SeekPreRoll>1</SeekPreRoll>
        <TrackTranslate>
          <TrackTranslateEditionUID>1</TrackTranslateEditionUID>
          <TrackTranslateCodec>1</TrackTranslateCodec>
          <TrackTranslateTrackID>1A45DFA3</TrackTranslateTrackID>
        </TrackTranslate>
        <Video>
          <FlagInterlaced>1</FlagInterlaced>
          <FieldOrder>1</FieldOrder>
          <StereoMode>1</StereoMode>
          <AlphaMode>1</AlphaMode>
          <OldStereoMode>1</OldStereoMode>
          <PixelWidth>1</PixelWidth>
          <PixelHeight>1</PixelHeight>
          <PixelCropBottom>1</PixelCropBottom>
          <PixelCropTop>1</PixelCropTop>
          <PixelCropLeft>1</PixelCropLeft>
          <PixelCropRight>1</PixelCropRight>
          <DisplayWidth>1</DisplayWidth>
          <DisplayHeight>1</DisplayHeight>
          <DisplayUnit>1</DisplayUnit>
          <AspectRatioType>1</AspectRatioType>
          <ColourSpace>1A45DFA3</ColourSpace>
          <GammaValue>0x1p+0</GammaValue>
          <FrameRate>0x1p+0</FrameRate>
          <Colour>
            <MatrixCoefficients>1</MatrixCoefficients>
            <BitsPerChannel>1</BitsPerChannel>
            <ChromaSubsamplingHorz>1</ChromaSubsamplingHorz>
            <ChromaSubsamplingVert>1</ChromaSubsamplingVert>
            <CbSubsamplingHorz>1</CbSubsamplingHorz>
            <CbSubsamplingVert>1</CbSubsamplingVert>
            <ChromaSitingHorz>1</ChromaSitingHorz>
            <ChromaSitingVert>1</ChromaSitingVert>
            <Range>1</Range>
            <TransferCharacteristics>1</TransferCharacteristics>
            <Primaries>1</Primaries>
            <MaxCLL>1</MaxCLL>
            <MaxFALL>1</MaxFALL>
            <MasteringMetadata>
              <PrimaryRChromaticityX>0x1p+0</PrimaryRChromaticityX>
              <PrimaryRChromaticityY>0x1p+0</PrimaryRChromaticityY>
              <PrimaryGChromaticityX>0x1p+0</PrimaryGChromaticityX>
              <PrimaryGChromaticityY>0x1p+0</PrimaryGChromaticityY>
              <PrimaryBChromaticityX>0x1p+0</PrimaryBChromaticityX>
              <PrimaryBChromaticityY>0x1p+0</PrimaryBChromaticityY>
              <WhitePointChromaticityX>0x1p+0</WhitePointChromaticityX>
              <WhitePointChromaticityY>0x1p+0</WhitePointChromaticityY>
              <LuminanceMax>0x1p+0</LuminanceMax>
              <LuminanceMin>0x1p+0</LuminanceMin>
            </MasteringMetadata>
          </Colour>
          <Projection>
            <ProjectionType>1</ProjectionType>
            <ProjectionPrivate>1A45DFA3</ProjectionPrivate>
            <ProjectionPoseYaw>0x1p+0</ProjectionPoseYaw>
            <ProjectionPosePitch>0x1p+0</ProjectionPosePitch>
            <ProjectionPoseRoll>0x1p+0</ProjectionPoseRoll>
          </Projection>
        </Video>
        <Audio>
          <SamplingFrequency>0x1p+0</SamplingFrequency>
          <OutputSamplingFrequency>0x1p+0</OutputSamplingFrequency>
          <Channels>1</Channels>
          <ChannelPositions>1A45DFA3</ChannelPositions>
          <BitDepth>1</BitDepth>
        </Audio>
        <TrackOperation>
          <TrackCombinePlanes>
            <TrackPlane>
              <TrackPlaneUID>1</TrackPlaneUID>
              <TrackPlaneType>1</TrackPlaneType>
            </TrackPlane>
          </TrackCombinePlanes>
          <TrackJoinBlocks>
            <TrackJoinUID>1</TrackJoinUID>
          </TrackJoinBlocks>
        </TrackOperation>
        <TrickTrackUID>1</TrickTrackUID>
        <TrickTrackSegmentUID>1A45DFA3</TrickTrackSegmentUID>
        <TrickTrackFlag>1</TrickTrackFlag>
        <TrickMasterTrackUID>1</TrickMasterTrackUID>
        <TrickMasterTrackSegmentUID>1A45DFA3</TrickMasterTrackSegmentUID>
        <ContentEncodings>
          <ContentEncoding>
            <ContentEncodingOrder>1</ContentEncodingOrder>
            <ContentEncodingScope>1</ContentEncodingScope>
            <ContentEncodingType>1</ContentEncodingType>
            <ContentCompression>
              <ContentCompAlgo>1</ContentCompAlgo>
              <ContentCompSettings>1A45DFA3</ContentCompSettings>
            </ContentCompression>
            <ContentEncryption>
              <ContentEncAlgo>1</ContentEncAlgo>
              <ContentEncKeyID>1A45DFA3</ContentEncKeyID>
              <ContentSignature>1A45DFA3</ContentSignature>
              <ContentSigKeyID>1A45DFA3</ContentSigKeyID>
              <ContentSigAlgo>1</ContentSigAlgo>
              <ContentSigHashAlgo>1</ContentSigHashAlgo>
            </ContentEncryption>
          </ContentEncoding>
        </ContentEncodings>
      </TrackEntry>
    </Tracks>
    <Cues>
      <CuePoint>
        <CueTime>1</CueTime>
        <CueTrackPositions>
          <CueTrack>1</CueTrack>
          <CueClusterPosition>1</CueClusterPosition>
          <CueRelativePosition>1</CueRelativePosition>
          <CueDuration>1</CueDuration>
          <CueBlockNumber>1</CueBlockNumber>
          <CueCodecState>1</CueCodecState>
          <CueReference>
            <CueRefTime>1</CueRefTime>
            <CueRefCluster>1</CueRefCluster>
            <CueRefNumber>1</CueRefNumber>
            <CueRefCodecState>1</CueRefCodecState>
          </CueReference>
        </CueTrackPositions>
      </CuePoint>
    </Cues>
    <Attachments>
      <AttachedFile>
        <FileDescription>utf-8</FileDescription>
        <FileName>utf-8</FileName>
        <FileMimeType>string</FileMimeType>
        <FileData>1A45DFA3</FileData>
        <FileUID>1</FileUID>
        <FileReferral>1A45DFA3</FileReferral>
        <FileUsedStartTime>1</FileUsedStartTime>
        <FileUsedEndTime>1</FileUsedEndTime>
      </AttachedFile>
    </Attachments>
    <Chapters>
      <EditionEntry>
        <EditionUID>1</EditionUID>
        <EditionFlagHidden>1</EditionFlagHidden>
        <EditionFlagDefault>1</EditionFlagDefault>
        <EditionFlagOrdered>1</EditionFlagOrdered>
      </EditionEntry>
      <ChapterAtom/>
    </Chapters>
    <Tags>
      <Tag>
        <Targets>
          <TargetTypeValue>1</TargetTypeValue>
          <TargetType>string</TargetType>
          <TagTrackUID>1</TagTrackUID>
          <TagEditionUID>1</TagEditionUID>
          <TagChapterUID>1</TagChapterUID>
          <TagAttachmentUID>1</TagAttachmentUID>
        </Targets>
      </Tag>
      <SimpleTag/>
    </Tags>
  </Segment>
</XEBML>
```

**Comment by dericed** [comment]
For the record the above xml fragment was made with the ebml_matroska.xml and xml starlet with this

```sh
#!/bin/bash
xml sel -t -m //element -v @name -o "," -v @type -o "," -v @path -n ebml_matroska.xml | sed 's|\\|/|g' > /tmp/elements.txt
echo "<XEBML/>" > xebml.xml
while read i ; do
    name=$(echo "$i" | cut -d, -f 1)
    type=$(echo "$i" | cut -d, -f 2)
    path=$(echo "$i" | cut -d, -f 3 | cut -d"(" -f2 | cut -d ")" -f1)
    parentpath=$(dirname "$path")
    if [[ "$parentpath" = "/" ]] ; then
        parentpath=""
    fi
    case $type in
        uinteger) value=(-v "1") ;;
        integer)  value=(-v "-1") ;;
        float)    value=(-v "0x1p+0") ;;
        date)     value=(-v "0") ;;
        binary)   value=(-v "1A45DFA3") ;;
        master)   value=() ;;
        utf-8)    value=(-v "utf-8") ;;
        string)   value=(-v "string") ;;
    esac
    xml ed -L -s "/XEBML${parentpath}" --type "elem" -n "${name}" "${value[@]}" xebml.xml
    echo "xml ed -L -s /XEBML${parentpath} --type elem -n ${name} ${value[@]} xebml.xml"
done < /tmp/elements.txt
```

**Comment by dericed** [comment]
ping. Any consensus on this approach or even if `XEBML` is worth defining.

**Comment by vi** [comment]
@dericed , Cues and SeekHeaads would be wrong in the round tripped mkv though this schema.

Note that there is already my tool for round tripping matroska though xml: [xml2mkv](https://github.com/vi/mkvparse/blob/master/xml2mkv) [mkv2xml](https://github.com/vi/mkvparse/blob/master/mkv2xml)

**Comment by dericed** [comment]
I use xml2mkv and mkv2xml regularly. It's very helpful for creating small sample files. Perhaps your standardized xml expression is the best starting place to define this. I think there's several places in the use and definition of Matroska where we need a consistent way to express sections of Matroska in a human readable way.

Thus far I've put this concept of XEBML into the EBML spec, though having it hear means that it needs to be format independent. Perhaps it's better to move this concept to the Matroska spec itself where it could be more specific to the qualities of Matroska.

**Comment by robUx4** [comment]
For junk data, I think it's useful. What about strings that have junk after the first `Null Octet` ?

This format means that the element names have to be picked carefully to look nice and meaningful in XML. Also that once set in stone, we cannot change a name easily.

**Comment by robUx4** [comment]
Also do we want this to be defined in the EBML specifications ? Or should it go in a separate specification ? it not be good to block the EBML specification for something that was never there in the first place.

**Comment by dericed** [comment]
I agree this shouldn't be blocking and it may be a larger effort than we're up for at the moment. We do however need to define a convention for expressing a Matroska fragment in text as this is used several times in the Matroska specification. Rather than a more global EBML solution I'll add this as a convention issue in Matroska.

**Comment by dericed** [comment]
Issue moved to https://github.com/Matroska-Org/matroska-specification/issues/129.

**Pull request closed without merging**
