### PR TITLE
clarify EBMLSchema namespace

### PR DESCRIPTION
**Pull request by dericed**
alternative to https://github.com/cellar-wg/ebml-specification/pull/387

### CODE REVIEW

**Comment by robUx4** [comment]
About the formatting, I think the ``` is overkill here. Simple backticks should be enough.
If that's OK I'll update this PR before I merge it.

**Comment by dericed** [comment]
changed to a simple backtick quote

**Comment by robUx4** [comment]
Turned it into a regular sentence. Otherwise it's just quoted text with missing punctuation.

**Comment by dericed** [comment]
Lgtm

**Pull request merged**
