### PR TITLE
Update to mmark 2.0.40

### PR DESCRIPTION
**Pull request by dericed**
Update RFC make process to use mmark 2.0.40. Similar in scope to https://github.com/FFmpeg/FFV1/pull/152.

### CODE REVIEW

**Comment by dericed** [comment]
any objection to updating the version of mmark we use?

**Comment by retokromer** [comment]
Not at all.

**Comment by robUx4** [comment]
What's the goal ?
It is not available on Debian at least https://packages.debian.org/search?keywords=mmark&searchon=names&suite=all&section=all

**Comment by robUx4** [comment]
I downloaded a [precompiled binary](https://github.com/mmarkdown/mmark/releases), the Makefile doesn't seem correct. It tries to process `draft-ietf-cellar-ebml-10.md` and then `draft-ietf-cellar-ebml-10.xml`. I think it's missing a `>` redirection.

After fixing that xml2fc (2.9.6 in my case, so more recent than the 2.5.1 advertised in the Makefile) fails to compile the produced XML file:
```
xml2rfc --html draft-ietf-cellar-ebml-10.xml -o draft-ietf-cellar-ebml-10.html
Parsing file draft-ietf-cellar-ebml-10.xml
ERROR: Unable to validate the XML document: draft-ietf-cellar-ebml-10.xml
 <string>: Line 577: IDREF attribute target references an unknown ID "RFC5234"
 <string>: Line 600: IDREF attribute target references an unknown ID "RFC5234"
 <string>: Line 689: IDREF attribute target references an unknown ID "RFC5646"
 <string>: Line 54: IDREF attribute target references an unknown ID "W3C.REC-xml-20081126"
 <string>: Line 484: IDREF attribute target references an unknown ID "W3C.REC-xml-20081126"
 <string>: Line 331: IDREF attribute target references an unknown ID "RFC3339"
 <string>: Line 484: IDREF attribute target references an unknown ID "W3C.REC-xmlschema-0-20010502"
 <string>: Line 317: IDREF attribute target references an unknown ID "IEEE.754.1985"
 <string>: Line 46: IDREF attribute target references an unknown ID "RFC8174"
 <string>: Line 995: IDREF attribute target references an unknown ID "ITU.V42.1994"
 <string>: Line 1059: IDREF attribute target references an unknown ID "RFC8126"
 <string>: Line 1060: IDREF attribute target references an unknown ID "RFC8126"
 <string>: Line 1062: IDREF attribute target references an unknown ID "RFC8126"
 <string>: Line 1068: IDREF attribute target references an unknown ID "RFC8126"
 <string>: Line 1135: IDREF attribute target references an unknown ID "RFC8126"
 <string>: Line 995: IDREF attribute target references an unknown ID "ISO.3309.1979"
 <string>: Line 46: IDREF attribute target references an unknown ID "RFC2119"
 <string>: Line 327: IDREF attribute target references an unknown ID "RFC3629"
 <string>: Line 322: IDREF attribute target references an unknown ID "RFC0020"
 <string>: Line 788: IDREF attribute target references an unknown ID "ISO.9899.2011"
 <string>: Line 577: IDREF attribute target references an unknown ID "RFC7405"
Makefile:16: recipe for target 'draft-ietf-cellar-ebml-10.html' failed
```

**Comment by dericed** [comment]
mmark 2.0.40 supports the newer xml2rfc format, which 1.3.4 does not. IETF still accepts the older format so perhaps we can wait for more repositories to update their mmark.

**Comment by dericed** [comment]
I checked and Debian still only supports up to mmark 1.3.6; however these versions are now [deprecated](https://github.com/miekg/mmark/commit/4a113919b52e731d8886e79b19292535937b8ce2), and the new repo for mmark contains versions 1.9.90 through 2.0.46 (which is supported by homebrew, the package manager I'm using for it). There may be more needed to address the errors, but is the stuck debian support blocking?

**Comment by robUx4** [comment]
I gave this another try with the latest 2.1.1 version. The output seems to be seriously bogus. For example it generates a `</front>` with no `<front>`, `VINT_DATA` becomes `VINT<em>DATA` in the text, etc.

I created a rough branch which downloads the Linux version and uses it:
https://github.com/cellar-wg/ebml-specification/tree/new_mmark

If you manage to make this version work for you...

**Comment by retokromer** [comment]
>`VINT_DATA` becomes `VINT<em>DATA` in the text

I guess, it’s because the underscore is not escaped. I’ll check if mmark needs an additional parameter in this version.

**Comment by robUx4** [comment]
Nevermind, I didn't notice that @dericed also add some fixes in the Markdown. These work. I'll update this PR with what I have.

**Comment by robUx4** [comment]
There's still an error with `[@!W3C.SPSD-xhtml-basic-20180327]` that I need to fix.
Also support downloading the proper mmark binary on various platforms.

**Comment by robUx4** [comment]
So it actually update to `2.1.1` and xml2rfc to `2.30.0`.

When this is merged we should do the same on Matroska.

**Comment by robUx4** [comment]
@dericed @JeromeMartinez @retokromer can you check that it builds for you
(don't forget to run ./boostrap first)

If your mmark/xml2rfc is recent enough it will use the system one. Otherwise it will download one locally and use that instead.

**Comment by dericed** [comment]
@robUx4, this works for me and thanks to your latest commit I didn't even have to run bootstrap. I'm going to merge.

**Comment by retokromer** [comment]
@robUx4 Yep, it works fine on my end as well.

**Pull request merged**
