### PR TITLE
All parents of unknownsizelement MUST also have unknownsizelement

### PR DESCRIPTION
**Pull request by robUx4**

### CODE REVIEW

**Comment by retokromer** [comment]
+1

**Comment by dericed** [comment]
suggested re-wording (since we discuss the definition of the EBML Element and not the EBML Element itself I prefer to use the word `define` rather than `has`:
```
An `EBML Element` that is defined with an `unknownsizeallowed` attribute set to 1 MUST also have the `unknownsizeallowed` attribute of its `Parent Element`  set to 1.
```

**Comment by robUx4** [comment]
I updated the PR with @dericed rewording

**Comment by dericed** [comment]
Minor new rewording:
> An `EBML Element` that is defined with an `unknownsizeallowed` attribute set to `1` MUST also have the `unknownsizeallowed` attribute of its `Parent Element`  (if any) set to `1`.

**Comment by retokromer** [comment]
LGTM

**Comment by mbunkus** [comment]
LGTM, too.

**Comment by robUx4** [comment]
I didn't like the `(if any)`. It MUST be set and that's not the default so it must be set anyway.

**Comment by robUx4** [comment]
The backtick of the `1` could be another patch that may be done for other ones as well.

**Pull request merged**
