### PR TITLE
Use a more stable and actual URL for namespace of our EBML Schema

### PR DESCRIPTION
**Pull request by robUx4**

### CODE REVIEW

**Review by mbunkus — APPROVED** [review]

**Review by retokromer — APPROVED** [review]

**Review by mbunkus — CHANGES_REQUESTED** [review]
Steve, please see Richard's reply on the CELLAR ML regarding preference of a URN over URL, and if URL which one to use.

**Comment by dericed** [comment]
I suggest that we also include a declaration of the namespace in the narrative of the RFC, equivalent of https://tools.ietf.org/html/rfc4826#section-3.4.4.

**Comment by dericed** [comment]
I also prefer `urn:ietf:rfc:8794` as well, particularly after reviewing @mcr's comments.

**Comment by robUx4** [comment]
Closing this in favor of #388

**Pull request closed without merging**
